// This file was generated by liblab | https://liblab.com/

using BookingClient;
using BookingClient.Config;
using BookingClient.Models;
using Environment = BookingClient.Http.Environment;

var apiKeyConfig = new ApiKeyAuthConfig("YOUR_API_KEY");

var config = new BookingClientConfig
{
    Environment = Environment.Default,
    AccessToken = "YOUR_ACCESS_TOKEN",
    ApiKeyAuth = apiKeyConfig
};

var client = new BookingClientClient(config);

var booker = new BookerInputDto("gt", BookerInputDto.Platform.Android);
var guests = new GuestsInputDto(5, 0);
var input = new SearchInputDto("checkin", "checkout", booker, guests);

var response = await client.DemandApiV3Compatible.SearchAsync(input, SearchAccept.ApplicationJson);

Console.WriteLine(response);
