// This file was generated by liblab | https://liblab.com/

namespace BookingClient.Config;

public record ApiKeyAuthConfig(
    string ApiKey,
    string? ApiKeyHeader = ApiKeyAuthConfig.DefaultApiKeyHeader
)
{
    public const string DefaultApiKeyHeader = "X-Affiliate-id";
}
