// This file was generated by liblab | https://liblab.com/

using Environment = BookingClient.Http.Environment;

namespace BookingClient.Config;

/// <summary>
/// Configuration options for the BookingClientClient.
/// </summary>
public record BookingClientConfig(
    /// <value>The environment to use for the SDK.</value>
    Environment? Environment = null,
    /// <value>The access token.</value>
    string? AccessToken = null,
    /// <value>The api-key authentication configuration.</value>
    ApiKeyAuthConfig? ApiKeyAuth = null
);
