// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace BookingClient.Models;

/// <summary>The exact allocation of guests to rooms.</summary>
public record AllocationInputDto(
    /// <value>The number of adults for this room.</value>
    [property: JsonPropertyName("number_of_adults")]
        long NumberOfAdults,
    /// <value>The children ages for this room.</value>
    [property:
        JsonPropertyName("children"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<long>? Children = null
);
