// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace BookingClient.Models;

/// <summary>
/// Alternate location to collect the key of this accommodation property.
/// This is returned if the key to access the property is in another location.
/// </summary>
public record AlternativeKeyLocationDto(
    [property:
        JsonPropertyName("address"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        object? Address = null,
    [property:
        JsonPropertyName("city"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        object? City = null,
    [property:
        JsonPropertyName("postal_code"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? PostalCode = null
);
