// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace BookingClient.Models;

/// <summary>Lists all alternative bed configurations that are supported.</summary>
public record BedConfigurationDto(
    /// <value>Uniquely identifies this bed configuration.</value>
    [property: JsonPropertyName("id"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        string? Id = null,
    /// <value>Detail list of all different types and number of beds included in this configuration.</value>
    [property:
        JsonPropertyName("configuration"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<BedDto>? Configuration = null
);
