// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace BookingClient.Models;

/// <summary>Detail list of all different types and number of beds included in this configuration.</summary>
public record BedDto(
    /// <value>A signed integer number that uniquely identifies a bed type. Examples of bed types are: Single, Double etc.</value>
    [property:
        JsonPropertyName("bed_type"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        long? BedType = null,
    /// <value>Number of similar beds included in this configuration.</value>
    [property:
        JsonPropertyName("number_of_beds"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        long? NumberOfBeds = null
);
