// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace BookingClient.Models;

public record BedroomDto(
    [property:
        JsonPropertyName("bed_configurations"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<BedConfigurationDto>? BedConfigurations = null
);
