// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace BookingClient.Models;

/// <summary>
/// The object containing all the relevant information for the combination of room, policy, meal and occupancy that determines the price."
/// A block is the unique entity you book with booking.com.
/// </summary>
public record BlockOutputDto(
    [property:
        JsonPropertyName("block_id"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? BlockId = null,
    [property:
        JsonPropertyName("breakfast_included"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        bool? BreakfastIncluded = null
);
