// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using BookingClient.Json;

namespace BookingClient.Models;

/// <summary>The booker's information.</summary>
public record BookerInputDto(
    /// <value>The booker country for showing the best price for that user and obeying laws regarding the display of taxes and fees.</value>
    [property: JsonPropertyName("country")]
        string Country,
    /// <value>The booker platform for showing the platform based deals and prices.</value>
    [property: JsonPropertyName("platform")]
        BookerInputDto.Platform Platform_,
    /// <value>The travel purpose of the booker.</value>
    [property:
        JsonPropertyName("travel_purpose"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        BookerInputDto.TravelPurpose? TravelPurpose_ = null,
    /// <value>The user groups that the booker is a member of.</value>
    [property:
        JsonPropertyName("user_groups"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<BookerInputDto.UserGroups>? UserGroups_ = null
)
{
    /// <summary>The booker platform for showing the platform based deals and prices.</summary>
    public record Platform : ValueEnum<string>
    {
        internal Platform(string value)
            : base(value) { }

        public Platform()
            : base("ANDROID") { }

        public static Platform Android = new("ANDROID");
        public static Platform Desktop = new("DESKTOP");
        public static Platform Ios = new("IOS");
        public static Platform Mobile = new("MOBILE");
        public static Platform Tablet = new("TABLET");
    }

    /// <summary>The travel purpose of the booker.</summary>
    public record TravelPurpose : ValueEnum<string>
    {
        internal TravelPurpose(string value)
            : base(value) { }

        public TravelPurpose()
            : base("BUSINESS") { }

        public static TravelPurpose Business = new("BUSINESS");
        public static TravelPurpose Leisure = new("LEISURE");
    }

    /// <summary>The user groups that the booker is a member of.</summary>
    public record UserGroups : ValueEnum<string>
    {
        internal UserGroups(string value)
            : base(value) { }

        public UserGroups()
            : base("AUTHENTICATED") { }

        public static UserGroups Authenticated = new("AUTHENTICATED");
        public static UserGroups Genius = new("GENIUS");
        public static UserGroups Genius2 = new("GENIUS2");
        public static UserGroups Genius3 = new("GENIUS3");
    }
}
