// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using BookingClient.Json;

namespace BookingClient.Models;

/// <summary>The cancellation policy for this product.</summary>
public record CancellationDto(
    /// <value>Until when the order for this product can be cancelled for free.</value>
    [property:
        JsonPropertyName("free_cancellation_until"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? FreeCancellationUntil = null,
    /// <value>The cancellation scheme supported by this product.</value>
    [property:
        JsonPropertyName("type"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        CancellationDto.Type_? Type_1 = null
)
{
    /// <summary>The cancellation scheme supported by this product.</summary>
    public record Type_ : ValueEnum<string>
    {
        internal Type_(string value)
            : base(value) { }

        public Type_()
            : base("FREE_CANCELLATION") { }

        public static Type_ FreeCancellation = new("FREE_CANCELLATION");
        public static Type_ NonRefundable = new("NON_REFUNDABLE");
        public static Type_ SpecialConditions = new("SPECIAL_CONDITIONS");
    }
}
