// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using BookingClient.Json;

namespace BookingClient.Models;

public record ConstantInputDto(
    /// <value>Allows to filter the results only for specific sections.</value>
    [property:
        JsonPropertyName("constants"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<ConstantInputDto.Constants>? Constants_ = null,
    [property:
        JsonPropertyName("languages"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<ConstantInputDto.ConstantInputDtoLanguages>? Languages = null
)
{
    /// <summary>Allows to filter the results only for specific sections.</summary>
    public record Constants : ValueEnum<string>
    {
        internal Constants(string value)
            : base(value) { }

        public Constants()
            : base("ACCOMMODATION_TYPES") { }

        public static Constants AccommodationTypes = new("ACCOMMODATION_TYPES");
        public static Constants AccommodationFacilities = new("ACCOMMODATION_FACILITIES");
        public static Constants AccommodationThemes = new("ACCOMMODATION_THEMES");
        public static Constants BedTypes = new("BED_TYPES");
        public static Constants FacilityTypes = new("FACILITY_TYPES");
        public static Constants ChargeTypes = new("CHARGE_TYPES");
        public static Constants RoomTypes = new("ROOM_TYPES");
        public static Constants RoomFacilities = new("ROOM_FACILITIES");
        public static Constants ReviewScores = new("REVIEW_SCORES");
    }

    public record ConstantInputDtoLanguages : ValueEnum<string>
    {
        internal ConstantInputDtoLanguages(string value)
            : base(value) { }

        public ConstantInputDtoLanguages()
            : base("AR") { }

        public static ConstantInputDtoLanguages Ar = new("AR");
        public static ConstantInputDtoLanguages Bg = new("BG");
        public static ConstantInputDtoLanguages Ca = new("CA");
        public static ConstantInputDtoLanguages Cs = new("CS");
        public static ConstantInputDtoLanguages Da = new("DA");
        public static ConstantInputDtoLanguages De = new("DE");
        public static ConstantInputDtoLanguages El = new("EL");
        public static ConstantInputDtoLanguages En = new("EN");
        public static ConstantInputDtoLanguages EnGb = new("EN_GB");
        public static ConstantInputDtoLanguages EnUs = new("EN_US");
        public static ConstantInputDtoLanguages Es = new("ES");
        public static ConstantInputDtoLanguages EsAr = new("ES_AR");
        public static ConstantInputDtoLanguages EsMx = new("ES_MX");
        public static ConstantInputDtoLanguages Et = new("ET");
        public static ConstantInputDtoLanguages Fi = new("FI");
        public static ConstantInputDtoLanguages Fr = new("FR");
        public static ConstantInputDtoLanguages He = new("HE");
        public static ConstantInputDtoLanguages Hi = new("HI");
        public static ConstantInputDtoLanguages Hr = new("HR");
        public static ConstantInputDtoLanguages Hu = new("HU");
        public static ConstantInputDtoLanguages Id = new("ID");
        public static ConstantInputDtoLanguages Is_ = new("IS");
        public static ConstantInputDtoLanguages It = new("IT");
        public static ConstantInputDtoLanguages Ja = new("JA");
        public static ConstantInputDtoLanguages Ka = new("KA");
        public static ConstantInputDtoLanguages Ko = new("KO");
        public static ConstantInputDtoLanguages Lt = new("LT");
        public static ConstantInputDtoLanguages Lv = new("LV");
        public static ConstantInputDtoLanguages Ms = new("MS");
        public static ConstantInputDtoLanguages Nl = new("NL");
        public static ConstantInputDtoLanguages No = new("NO");
        public static ConstantInputDtoLanguages Pl = new("PL");
        public static ConstantInputDtoLanguages PtBr = new("PT_BR");
        public static ConstantInputDtoLanguages PtPt = new("PT_PT");
        public static ConstantInputDtoLanguages Ro = new("RO");
        public static ConstantInputDtoLanguages Ru = new("RU");
        public static ConstantInputDtoLanguages Sk = new("SK");
        public static ConstantInputDtoLanguages Sl = new("SL");
        public static ConstantInputDtoLanguages Sr = new("SR");
        public static ConstantInputDtoLanguages Sv = new("SV");
        public static ConstantInputDtoLanguages Th = new("TH");
        public static ConstantInputDtoLanguages Tl = new("TL");
        public static ConstantInputDtoLanguages Tr = new("TR");
        public static ConstantInputDtoLanguages Uk = new("UK");
        public static ConstantInputDtoLanguages Vi = new("VI");
        public static ConstantInputDtoLanguages ZhCn = new("ZH_CN");
        public static ConstantInputDtoLanguages ZhTw = new("ZH_TW");
    }
}
