// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace BookingClient.Models;

/// <summary>Contact information of the accommodation.</summary>
public record ContactsDto(
    /// <value>Contact information of the accommodation. It can be `null` if the data is missing.</value>
    [property:
        JsonPropertyName("general"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        ContactDto? General = null,
    /// <value>Contact information of the accommodation. It can be `null` if the data is missing.</value>
    [property:
        JsonPropertyName("reservations"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        ContactDto? Reservations = null
);
