// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace BookingClient.Models;

/// <summary>Limit the result list to the specified coordinates.</summary>
public record Coordinates(
    /// <value>Specify a latitude (as well as a longitude and radius) to do searches around a specific location.</value>
    [property: JsonPropertyName("latitude")]
        double Latitude,
    /// <value>Specify a longitude (as well as a latitude and radius) to do searches around a specific location.</value>
    [property: JsonPropertyName("longitude")]
        double Longitude,
    /// <value>The radius is km to search around the specified latitude and longitude.</value>
    [property: JsonPropertyName("radius")]
        double Radius
);
