// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace BookingClient.Models;

/// <summary>A signed integer number that uniquely identifies a city.</summary>
public record CoordinatesDto(
    /// <value>Latitude.</value>
    [property:
        JsonPropertyName("latitude"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? Latitude = null,
    /// <value>Longitude.</value>
    [property:
        JsonPropertyName("longitude"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? Longitude = null
);
