// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using BookingClient.Json;

namespace BookingClient.Models;

/// <summary>This specifies the deal tagging for the product.</summary>
public record DealDto(
    [property:
        JsonPropertyName("discount_percentage"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        long? DiscountPercentage = null,
    [property:
        JsonPropertyName("public_price"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? PublicPrice = null,
    [property:
        JsonPropertyName("tags"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<DealDto.Tags>? Tags_ = null
)
{
    public record Tags : ValueEnum<string>
    {
        internal Tags(string value)
            : base(value) { }

        public Tags()
            : base("BLACK_FRIDAY") { }

        public static Tags BlackFriday = new("BLACK_FRIDAY");
        public static Tags Genius = new("GENIUS");
        public static Tags LimitedTimeDeal = new("LIMITED_TIME_DEAL");
        public static Tags LoggedInDeal = new("LOGGED_IN_DEAL");
        public static Tags MobileRate = new("MOBILE_RATE");
        public static Tags SeasonalDeal = new("SEASONAL_DEAL");
    }
}
