// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace BookingClient.Models;

/// <summary>Textual information about the accommodation. Requires `{"extras":["description"]}`.</summary>
public record DescriptionDto(
    /// <value>Text containing important information about the property. The value is translated in the requested languages.</value>
    [property:
        JsonPropertyName("important_information"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        TranslationInformation? ImportantInformation = null,
    /// <value>List of all the license numbers of this accommodation property.</value>
    [property:
        JsonPropertyName("license_numbers"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<string>? LicenseNumbers = null,
    /// <value>
    /// The translated description text of this accommodation property in the requested languages.
    /// The maximum number of characters returned may be limited by contract.
    /// </value>
    [property:
        JsonPropertyName("text"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        TruncatedString? Text = null
);
