// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace BookingClient.Models;

/// <summary>The charge breakdown. Includes taxes and fees.</summary>
public record ExtraChargesDtoDouble(
    /// <value>Charges not included in 'book'.</value>
    [property:
        JsonPropertyName("excluded"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? Excluded = null,
    /// <value>Charges included in 'book'.</value>
    [property:
        JsonPropertyName("included"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? Included = null,
    [property:
        JsonPropertyName("conditional"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? Conditional = null
);
