// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using BookingClient.Json;

namespace BookingClient.Models;

/// <summary>The list of facilities available in this property. Requires `{"extras":["facilities"]}`.</summary>
public record FacilityDto(
    /// <value>
    /// A signed integer number that uniquely identifies an accommodation property facility.
    /// Examples of facilities are: Parking, Restaurant, Room service etc.
    /// </value>
    [property: JsonPropertyName("id"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        long? Id = null,
    /// <value>List of optional attributes for this facility.</value>
    [property:
        JsonPropertyName("attributes"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<FacilityDto.FacilityDtoAttributes>? Attributes = null
)
{
    /// <summary>List of optional attributes for this facility.</summary>
    public record FacilityDtoAttributes : ValueEnum<string>
    {
        internal FacilityDtoAttributes(string value)
            : base(value) { }

        public FacilityDtoAttributes()
            : base("OFFSITE") { }

        public static FacilityDtoAttributes Offsite = new("OFFSITE");
        public static FacilityDtoAttributes Paid = new("PAID");
    }
}
