// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using BookingClient.Json;

namespace BookingClient.Models;

public record GetAccommodationConstantsAccept : ValueEnum<string>
{
    internal GetAccommodationConstantsAccept(string value)
        : base(value) { }

    public GetAccommodationConstantsAccept()
        : base("application/json") { }

    public static GetAccommodationConstantsAccept ApplicationJson = new("application/json");
}
