// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using BookingClient.Json;

namespace BookingClient.Models;

public record GetHotelsReviewScoresAccept : ValueEnum<string>
{
    internal GetHotelsReviewScoresAccept(string value)
        : base(value) { }

    public GetHotelsReviewScoresAccept()
        : base("application/json, application/xml") { }

    public static GetHotelsReviewScoresAccept ApplicationJsonApplicationXml =
        new("application/json, application/xml");
}
