// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using BookingClient.Json;

namespace BookingClient.Models;

public record GetHotelTypesAccept : ValueEnum<string>
{
    internal GetHotelTypesAccept(string value)
        : base(value) { }

    public GetHotelTypesAccept()
        : base("application/json") { }

    public static GetHotelTypesAccept ApplicationJson = new("application/json");
}
