// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using BookingClient.Json;

namespace BookingClient.Models;

public record GetHotelThemeTypesAccept : ValueEnum<string>
{
    internal GetHotelThemeTypesAccept(string value)
        : base(value) { }

    public GetHotelThemeTypesAccept()
        : base("application/json") { }

    public static GetHotelThemeTypesAccept ApplicationJson = new("application/json");
}
