// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using BookingClient.Json;

namespace BookingClient.Models;

public record GetRoomFacilityTypesAccept : ValueEnum<string>
{
    internal GetRoomFacilityTypesAccept(string value)
        : base(value) { }

    public GetRoomFacilityTypesAccept()
        : base("application/json") { }

    public static GetRoomFacilityTypesAccept ApplicationJson = new("application/json");
}
