// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace BookingClient.Models;

/// <summary>The guest details for the request.</summary>
public record GuestsInputDto(
    /// <value>The number of adults for the search.</value>
    [property: JsonPropertyName("number_of_adults")]
        long NumberOfAdults,
    /// <value>The number of rooms needed.</value>
    [property: JsonPropertyName("number_of_rooms")]
        long NumberOfRooms,
    /// <value>The exact allocation of guests to rooms.</value>
    [property:
        JsonPropertyName("allocation"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<AllocationInputDto>? Allocation = null,
    /// <value>Array with the children ages.</value>
    [property:
        JsonPropertyName("children"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<long>? Children = null
);
