// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace BookingClient.Models;

/// <summary>Photos specific information of the hotel.</summary>
public record HotelPhotoDto(
    /// <value>Is this the main hotel photo.</value>
    [property:
        JsonPropertyName("main_photo"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        bool? MainPhoto = null,
    /// <value>Url of the photo with max width of 500 pixels.</value>
    [property:
        JsonPropertyName("url_original"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? UrlOriginal = null
);
