// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace BookingClient.Models;

public record HotelFacilityTypeOutputDto(
    /// <value>Unique ID of the hotel facility type.</value>
    [property:
        JsonPropertyName("hotel_facility_type_id"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        long? HotelFacilityTypeId = null,
    /// <value>The type of facility this is, mapped from FacilityTypes.</value>
    [property:
        JsonPropertyName("facility_type_id"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        long? FacilityTypeId = null,
    /// <value>The name of this facility type in english.</value>
    [property:
        JsonPropertyName("name"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? Name = null,
    /// <value>The fields and their translations in various languages. They are only shown if we have the translations available.</value>
    [property:
        JsonPropertyName("translations"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<TranslationDto>? Translations = null
);
