// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace BookingClient.Models;

public record HotelsOutputDto(
    /// <value>Hotel specific information.</value>
    [property:
        JsonPropertyName("hotel_data"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        HotelDataDto? HotelData = null,
    /// <value>Unique ID to represent this hotel.</value>
    [property:
        JsonPropertyName("hotel_id"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        long? HotelId = null,
    /// <value>This block has room data for this hotel.</value>
    [property:
        JsonPropertyName("room_data"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<RoomDataDto>? RoomData = null
);
