// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace BookingClient.Models;

public record HotelAvailabilityOutputDto(
    /// <value>The unique identifier of this hotel.</value>
    [property:
        JsonPropertyName("hotel_id"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        long? HotelId = null,
    /// <value>The currency code of the hotel's currency.</value>
    [property:
        JsonPropertyName("hotel_currency_code"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? HotelCurrencyCode = null,
    /// <value>The display price of the room in this hotel.</value>
    [property:
        JsonPropertyName("price"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? Price = null,
    /// <value>The net price (price without charges) of the room in this hotel.</value>
    [property:
        JsonPropertyName("net_price"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? NetPrice = null
);
