// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using BookingClient.Json;

namespace BookingClient.Models;

public record HotelFacilityInputDto(
    /// <value>Limit the results to these facility types.</value>
    [property:
        JsonPropertyName("facility_type_ids"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<long>? FacilityTypeIds = null,
    /// <value>Limit the results to these hotel facility types.</value>
    [property:
        JsonPropertyName("hotel_facility_type_ids"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<long>? HotelFacilityTypeIds = null,
    /// <value>
    /// Limit the results to these languages.
    /// Please check the "Possible Values" section of the documentation for the accepted language codes.
    /// </value>
    [property:
        JsonPropertyName("languages"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<HotelFacilityInputDto.HotelFacilityInputDtoLanguages>? Languages = null
)
{
    /// <summary>
    /// Limit the results to these languages.
    /// Please check the "Possible Values" section of the documentation for the accepted language codes.
    /// </summary>
    public record HotelFacilityInputDtoLanguages : ValueEnum<string>
    {
        internal HotelFacilityInputDtoLanguages(string value)
            : base(value) { }

        public HotelFacilityInputDtoLanguages()
            : base("AR") { }

        public static HotelFacilityInputDtoLanguages Ar = new("AR");
        public static HotelFacilityInputDtoLanguages Bg = new("BG");
        public static HotelFacilityInputDtoLanguages Ca = new("CA");
        public static HotelFacilityInputDtoLanguages Cs = new("CS");
        public static HotelFacilityInputDtoLanguages Da = new("DA");
        public static HotelFacilityInputDtoLanguages De = new("DE");
        public static HotelFacilityInputDtoLanguages El = new("EL");
        public static HotelFacilityInputDtoLanguages En = new("EN");
        public static HotelFacilityInputDtoLanguages EnGb = new("EN_GB");
        public static HotelFacilityInputDtoLanguages EnUs = new("EN_US");
        public static HotelFacilityInputDtoLanguages Es = new("ES");
        public static HotelFacilityInputDtoLanguages EsAr = new("ES_AR");
        public static HotelFacilityInputDtoLanguages EsMx = new("ES_MX");
        public static HotelFacilityInputDtoLanguages Et = new("ET");
        public static HotelFacilityInputDtoLanguages Fi = new("FI");
        public static HotelFacilityInputDtoLanguages Fr = new("FR");
        public static HotelFacilityInputDtoLanguages He = new("HE");
        public static HotelFacilityInputDtoLanguages Hi = new("HI");
        public static HotelFacilityInputDtoLanguages Hr = new("HR");
        public static HotelFacilityInputDtoLanguages Hu = new("HU");
        public static HotelFacilityInputDtoLanguages Id = new("ID");
        public static HotelFacilityInputDtoLanguages Is_ = new("IS");
        public static HotelFacilityInputDtoLanguages It = new("IT");
        public static HotelFacilityInputDtoLanguages Ja = new("JA");
        public static HotelFacilityInputDtoLanguages Ka = new("KA");
        public static HotelFacilityInputDtoLanguages Ko = new("KO");
        public static HotelFacilityInputDtoLanguages Lt = new("LT");
        public static HotelFacilityInputDtoLanguages Lv = new("LV");
        public static HotelFacilityInputDtoLanguages Ms = new("MS");
        public static HotelFacilityInputDtoLanguages Nl = new("NL");
        public static HotelFacilityInputDtoLanguages No = new("NO");
        public static HotelFacilityInputDtoLanguages Pl = new("PL");
        public static HotelFacilityInputDtoLanguages PtBr = new("PT_BR");
        public static HotelFacilityInputDtoLanguages PtPt = new("PT_PT");
        public static HotelFacilityInputDtoLanguages Ro = new("RO");
        public static HotelFacilityInputDtoLanguages Ru = new("RU");
        public static HotelFacilityInputDtoLanguages Sk = new("SK");
        public static HotelFacilityInputDtoLanguages Sl = new("SL");
        public static HotelFacilityInputDtoLanguages Sr = new("SR");
        public static HotelFacilityInputDtoLanguages Sv = new("SV");
        public static HotelFacilityInputDtoLanguages Th = new("TH");
        public static HotelFacilityInputDtoLanguages Tl = new("TL");
        public static HotelFacilityInputDtoLanguages Tr = new("TR");
        public static HotelFacilityInputDtoLanguages Uk = new("UK");
        public static HotelFacilityInputDtoLanguages Vi = new("VI");
        public static HotelFacilityInputDtoLanguages ZhCn = new("ZH_CN");
        public static HotelFacilityInputDtoLanguages ZhTw = new("ZH_TW");
    }
}
