// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace BookingClient.Models;

public record KeyCollectionInformationDto(
    /// <value>
    /// Alternate location to collect the key of this accommodation property.
    /// This is returned if the key to access the property is in another location.
    /// </value>
    [property:
        JsonPropertyName("alternate_location"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        AlternativeKeyLocationDto? AlternateLocation = null,
    /// <value>
    /// An enumeration that describes the conditions for the checkin process and for collecting the key to access the property.
    /// This is typically relevant for non-hotel accommodations (like houses or apartments) without a 24 hours front-desk.
    /// </value>
    [property:
        JsonPropertyName("checkin_method"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? CheckinMethod = null,
    /// <value>Location of the key to access this accommodation property.</value>
    [property:
        JsonPropertyName("key_location"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? KeyLocation = null
);
