// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace BookingClient.Models;

/// <summary>Translated accommodation address.</summary>
public record LazyTranslatedString(
    [property:
        JsonPropertyName("fallback"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? Fallback = null
);
