// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace BookingClient.Models;

/// <summary>The time till when checkout can be done at this property.</summary>
public record LocalTime(
    [property:
        JsonPropertyName("hour"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        long? Hour = null,
    [property:
        JsonPropertyName("minute"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        long? Minute = null,
    [property:
        JsonPropertyName("second"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        long? Second = null,
    [property:
        JsonPropertyName("nano"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        long? Nano = null
);
