// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace BookingClient.Models;

/// <summary>Total rooms available.</summary>
public record NumberOfRoomsDto(
    [property:
        JsonPropertyName("bathrooms"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        long? Bathrooms = null,
    [property:
        JsonPropertyName("bedrooms"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        long? Bedrooms = null,
    [property:
        JsonPropertyName("living_rooms"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        long? LivingRooms = null
);
