// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using BookingClient.Json;

namespace BookingClient.Models;

/// <summary>Payment terms and conditions for this product.</summary>
public record PaymentDto(
    [property:
        JsonPropertyName("payment_types"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<PaymentDto.PaymentTypes>? PaymentTypes_ = null
)
{
    public record PaymentTypes : ValueEnum<string>
    {
        internal PaymentTypes(string value)
            : base(value) { }

        public PaymentTypes()
            : base("PAY_LATER") { }

        public static PaymentTypes PayLater = new("PAY_LATER");
        public static PaymentTypes PayNow = new("PAY_NOW");
    }
}
