// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace BookingClient.Models;

public record PhotoUrlDto(
    /// <value>URL of the photo image with a maximum width of 1280 pixels.</value>
    [property:
        JsonPropertyName("large"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? Large = null,
    /// <value>URL of the photo image with a maximum width of 500 pixels.</value>
    [property:
        JsonPropertyName("standard"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? Standard = null,
    /// <value>URL of the photo thumbnail image with dimensions 100x100 pixels.</value>
    [property:
        JsonPropertyName("thumbnail"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? Thumbnail = null,
    /// <value>URL of the photo thumbnail image with dimensions 300x300 pixels.</value>
    [property:
        JsonPropertyName("thumbnail_large"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? ThumbnailLarge = null
);
