// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace BookingClient.Models;

public record PhotoDto(
    /// <value>Flags this as the main photo. Not returned otherwise.</value>
    [property:
        JsonPropertyName("main_photo"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        bool? MainPhoto = null,
    /// <value>A list of tags associated with the photo. Manually generated.</value>
    [property:
        JsonPropertyName("tags"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<string>? Tags = null,
    [property: JsonPropertyName("url"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        PhotoUrlDto? Url = null
);
