// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace BookingClient.Models;

/// <summary>The policies for this product.</summary>
public record PoliciesDto(
    /// <value>The cancellation policy for this product.</value>
    [property:
        JsonPropertyName("cancellation"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        CancellationDto? Cancellation = null,
    /// <value>The meal plan policy for this product.</value>
    [property:
        JsonPropertyName("meal_plan"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        MealPlanDto? MealPlan = null,
    /// <value>Payment terms and conditions for this product.</value>
    [property:
        JsonPropertyName("payment"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        PaymentDto? Payment = null
);
