// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using BookingClient.Json;

namespace BookingClient.Models;

public record PostDetailsAccept : ValueEnum<string>
{
    internal PostDetailsAccept(string value)
        : base(value) { }

    public PostDetailsAccept()
        : base("application/json") { }

    public static PostDetailsAccept ApplicationJson = new("application/json");
}
