// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace BookingClient.Models;

/// <summary>
/// The price components of this product or selection of products.
/// 'base' and 'extra_charges' are returned only when explicitly requested (via 'extras=extra_charges').
/// </summary>
public record PriceDataDtoDouble(
    /// <value>The base price. Does not include any extra charges.</value>
    [property:
        JsonPropertyName("base"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? Base_ = null,
    /// <value>The price that will be charged by Booking.com.</value>
    [property:
        JsonPropertyName("book"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? Book = null,
    /// <value>The total price. Includes all extra charges.</value>
    [property:
        JsonPropertyName("total"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? Total = null,
    /// <value>The charge breakdown. Includes taxes and fees.</value>
    [property:
        JsonPropertyName("extra_charges"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        ExtraChargesDtoDouble? ExtraCharges = null
);
