// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace BookingClient.Models;

public record ProductDto(
    /// <value>Unique ID of the product.</value>
    [property: JsonPropertyName("id"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        string? Id = null,
    /// <value>The policies for this product.</value>
    [property:
        JsonPropertyName("policies"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        PoliciesDto? Policies = null,
    /// <value>
    /// The price components of this product or selection of products.
    /// 'base' and 'extra_charges' are returned only when explicitly requested (via 'extras=extra_charges').
    /// </value>
    [property:
        JsonPropertyName("price"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        PriceDataDtoListChargeDto? Price = null,
    /// <value>This specifies the deal tagging for the product.</value>
    [property:
        JsonPropertyName("deal"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        DealDto? Deal = null
);
