// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace BookingClient.Models;

/// <summary>Details of programmes undergone by the property.</summary>
public record ProgramSettingsDto(
    /// <value>Boolean value is "true" if property has travel proud badge and "false" otherwise.</value>
    [property:
        JsonPropertyName("travel_proud"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        bool? TravelProud = null
);
