// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace BookingClient.Models;

/// <summary>Review scores per question.</summary>
public record QuestionDto(
    /// <value>Number of reviewers that answered the question.</value>
    [property:
        JsonPropertyName("count"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        long? Count = null,
    /// <value>Localized question text. See language=... input parameter.</value>
    [property:
        JsonPropertyName("question"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? Question = null,
    /// <value>Question literal.</value>
    [property:
        JsonPropertyName("question_literal"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? QuestionLiteral = null,
    /// <value>Average score that reviewers provided in response to this question.</value>
    [property:
        JsonPropertyName("score"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? Score = null
);
