// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace BookingClient.Models;

public record ResponseOutputV2HotelTypesOutputDto(
    [property:
        JsonPropertyName("meta"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        Meta? Meta = null,
    [property:
        JsonPropertyName("result"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<HotelTypesOutputDto>? Result = null
);
