// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using BookingClient.Json;

namespace BookingClient.Models;

public record ReviewScoresInputDto(
    /// <value>List of hotel ids for which review score information should be displayed.</value>
    [property: JsonPropertyName("hotel_ids")]
        List<long> HotelIds,
    /// <value>Can be used to specify the affiliate id that should be used instead of the default one.</value>
    [property:
        JsonPropertyName("affiliate_id"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        long? AffiliateId = null,
    /// <value>
    /// Code of the language used to render response.
    /// Please check the "Possible Values" section of the documentation for the accepted language codes.
    /// </value>
    [property:
        JsonPropertyName("language"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        ReviewScoresInputDto.ReviewScoresInputDtoLanguage? Language = null,
    /// <value>Limits reviews to those written by specific reviewer type.</value>
    [property:
        JsonPropertyName("reviewer_type"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        ReviewScoresInputDto.ReviewerType? ReviewerType_ = null
)
{
    /// <summary>
    /// Code of the language used to render response.
    /// Please check the "Possible Values" section of the documentation for the accepted language codes.
    /// </summary>
    public record ReviewScoresInputDtoLanguage : ValueEnum<string>
    {
        internal ReviewScoresInputDtoLanguage(string value)
            : base(value) { }

        public ReviewScoresInputDtoLanguage()
            : base("AR") { }

        public static ReviewScoresInputDtoLanguage Ar = new("AR");
        public static ReviewScoresInputDtoLanguage Bg = new("BG");
        public static ReviewScoresInputDtoLanguage Ca = new("CA");
        public static ReviewScoresInputDtoLanguage Cs = new("CS");
        public static ReviewScoresInputDtoLanguage Da = new("DA");
        public static ReviewScoresInputDtoLanguage De = new("DE");
        public static ReviewScoresInputDtoLanguage El = new("EL");
        public static ReviewScoresInputDtoLanguage En = new("EN");
        public static ReviewScoresInputDtoLanguage EnGb = new("EN_GB");
        public static ReviewScoresInputDtoLanguage EnUs = new("EN_US");
        public static ReviewScoresInputDtoLanguage Es = new("ES");
        public static ReviewScoresInputDtoLanguage EsAr = new("ES_AR");
        public static ReviewScoresInputDtoLanguage EsMx = new("ES_MX");
        public static ReviewScoresInputDtoLanguage Et = new("ET");
        public static ReviewScoresInputDtoLanguage Fi = new("FI");
        public static ReviewScoresInputDtoLanguage Fr = new("FR");
        public static ReviewScoresInputDtoLanguage He = new("HE");
        public static ReviewScoresInputDtoLanguage Hi = new("HI");
        public static ReviewScoresInputDtoLanguage Hr = new("HR");
        public static ReviewScoresInputDtoLanguage Hu = new("HU");
        public static ReviewScoresInputDtoLanguage Id = new("ID");
        public static ReviewScoresInputDtoLanguage Is_ = new("IS");
        public static ReviewScoresInputDtoLanguage It = new("IT");
        public static ReviewScoresInputDtoLanguage Ja = new("JA");
        public static ReviewScoresInputDtoLanguage Ka = new("KA");
        public static ReviewScoresInputDtoLanguage Ko = new("KO");
        public static ReviewScoresInputDtoLanguage Lt = new("LT");
        public static ReviewScoresInputDtoLanguage Lv = new("LV");
        public static ReviewScoresInputDtoLanguage Ms = new("MS");
        public static ReviewScoresInputDtoLanguage Nl = new("NL");
        public static ReviewScoresInputDtoLanguage No = new("NO");
        public static ReviewScoresInputDtoLanguage Pl = new("PL");
        public static ReviewScoresInputDtoLanguage PtBr = new("PT_BR");
        public static ReviewScoresInputDtoLanguage PtPt = new("PT_PT");
        public static ReviewScoresInputDtoLanguage Ro = new("RO");
        public static ReviewScoresInputDtoLanguage Ru = new("RU");
        public static ReviewScoresInputDtoLanguage Sk = new("SK");
        public static ReviewScoresInputDtoLanguage Sl = new("SL");
        public static ReviewScoresInputDtoLanguage Sr = new("SR");
        public static ReviewScoresInputDtoLanguage Sv = new("SV");
        public static ReviewScoresInputDtoLanguage Th = new("TH");
        public static ReviewScoresInputDtoLanguage Tl = new("TL");
        public static ReviewScoresInputDtoLanguage Tr = new("TR");
        public static ReviewScoresInputDtoLanguage Uk = new("UK");
        public static ReviewScoresInputDtoLanguage Vi = new("VI");
        public static ReviewScoresInputDtoLanguage ZhCn = new("ZH_CN");
        public static ReviewScoresInputDtoLanguage ZhTw = new("ZH_TW");
    }

    /// <summary>Limits reviews to those written by specific reviewer type.</summary>
    public record ReviewerType : ValueEnum<string>
    {
        internal ReviewerType(string value)
            : base(value) { }

        public ReviewerType()
            : base("SOLO_TRAVELLER") { }

        public static ReviewerType SoloTraveller = new("SOLO_TRAVELLER");
        public static ReviewerType YoungCouple = new("YOUNG_COUPLE");
        public static ReviewerType MatureCouple = new("MATURE_COUPLE");
        public static ReviewerType FamilyWithYoungChildren = new("FAMILY_WITH_YOUNG_CHILDREN");
        public static ReviewerType FamilyWithOlderChildren = new("FAMILY_WITH_OLDER_CHILDREN");
        public static ReviewerType WithFriends = new("WITH_FRIENDS");
        public static ReviewerType Group = new("GROUP");
        public static ReviewerType ReviewCategoryCouples = new("REVIEW_CATEGORY_COUPLES");
        public static ReviewerType ReviewCategoryFamilies = new("REVIEW_CATEGORY_FAMILIES");
        public static ReviewerType ReviewCategoryGroupOfFriends =
            new("REVIEW_CATEGORY_GROUP_OF_FRIENDS");
        public static ReviewerType ReviewCategoryBusinessTravellers =
            new("REVIEW_CATEGORY_BUSINESS_TRAVELLERS");
    }
}
