// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace BookingClient.Models;

public record RoomOccupancyDto(
    [property:
        JsonPropertyName("allow_cribs_and_extra_beds"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        bool? AllowCribsAndExtraBeds = null,
    [property:
        JsonPropertyName("max_adults"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        long? MaxAdults = null,
    [property:
        JsonPropertyName("max_children"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        long? MaxChildren = null,
    [property:
        JsonPropertyName("max_cribs"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        long? MaxCribs = null,
    [property:
        JsonPropertyName("max_extra_beds"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        long? MaxExtraBeds = null,
    [property:
        JsonPropertyName("max_occupancy"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        long? MaxOccupancy = null
);
