// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace BookingClient.Models;

/// <summary>This block has room data for this hotel.</summary>
public record RoomDataDto(
    [property:
        JsonPropertyName("room_id"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        long? RoomId = null,
    [property:
        JsonPropertyName("room_info"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        RoomInfoDto? RoomInfo = null
);
