// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace BookingClient.Models;

/// <summary>A breakdown of all review scores into buckets 1 - 10.</summary>
public record ScoreDistribution(
    /// <value>Total number of reviews in this bucket.</value>
    [property:
        JsonPropertyName("count"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        long? Count = null,
    /// <value>Percent of score distribution that went into this bucket.</value>
    [property:
        JsonPropertyName("percent"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? Percent = null,
    /// <value>The bucket's review score value (1 - 10).</value>
    [property:
        JsonPropertyName("score"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        long? Score = null
);
