// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using BookingClient.Json;

namespace BookingClient.Models;

public record SearchAccept : ValueEnum<string>
{
    internal SearchAccept(string value)
        : base(value) { }

    public SearchAccept()
        : base("application/json") { }

    public static SearchAccept ApplicationJson = new("application/json");
}
