// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace BookingClient.Models;

/// <summary>Text containing important information about the property. The value is translated in the requested languages.</summary>
public record TranslationInformation(
    /// <value>Translated description of this room. The maximum number of characters returned may be limited by contract.</value>
    [property:
        JsonPropertyName("translated_string"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        TranslatedString? TranslatedString = null,
    [property:
        JsonPropertyName("non_lazy_translations"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        object? NonLazyTranslations = null
);
