// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace BookingClient.Models;

/// <summary>Translated description of this room. The maximum number of characters returned may be limited by contract.</summary>
public record TranslatedString(
    [property:
        JsonPropertyName("translations"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        object? Translations = null
);
