// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace BookingClient.Models;

/// <summary>
/// The translated description text of this accommodation property in the requested languages.
/// The maximum number of characters returned may be limited by contract.
/// </summary>
public record TruncatedString(
    [property:
        JsonPropertyName("truncate"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        bool? Truncate = null,
    /// <value>Translated description of this room. The maximum number of characters returned may be limited by contract.</value>
    [property:
        JsonPropertyName("translated_string"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        TranslatedString? TranslatedString = null
);
